### ISSUE TITLE
Getting an error when I run `npx create-socket-app -h` 

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/create-socket-app#15]
this is the error I'm getting : 
```
C:\Users\lamia\test>npx create-socket-app -h
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, scandir 'C:\C:\Users\lamia\AppData\Local\npm-cache\_npx\d5a408ba81afe2c4\node_modules\create-socket-app\templates'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\C:\\Users\\lamia\\AppData\\Local\\npm-cache\\_npx\\d5a408ba81afe2c4\\node_modules\\create-socket-app\\templates'
}

Node.js v18.13.0
```

**Comment by wujekbizon** [comment]
I had the same error, when trying to run create-socket-app. It's seems that there is a problem with the path. I found the answer here at this [link](https://github.com/socketsupply/create-socket-app/commit/f87503a0f4e87adc86b9b042693fc0cee417bd5d)
 

So after changing manually the line 10 it's working now, but there is another issue at least for me :
Now I've got this error :
```npx create-socket-app
Initializing npm package...OK
Installing developer dependencies...OK
Installing '@socketsupply/socket' locally (ssc not in PATH)
Installing dependencies...OK
Adding package scripts...OK
Creating socket files...   
Unable to create socket files: Error: Command failed: npm run init-project
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@socketsupply/socket-win32-x64' imported from C:\React\socket\node_modules\@socketsupply\socket\bin\ssc.js
    at new NodeError (node:internal/errors:399:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14) {
  code: 'ERR_MODULE_NOT_FOUND'
}

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
OK
Updating project configuration...
Unable to read socket.ini: Error: ENOENT: no such file or directory, open 'C:\React\socket\socket.ini'```

**Comment by lamiazar** [comment]
cc @mribbons  ^

**Comment by mribbons** [comment]
Hey @lamiazar and @wujekbizon,
The win32 package hasn't landed yet, I'm looking to get https://github.com/socketsupply/socket/pull/166 merged ASAP.

**Comment by wujekbizon** [comment]
Just want to let you all know, that everything working for me now. I can call create-socket-app react and it's working perfectly.
Now I can start building something :).
There is only one small issue more like a detail , clang++  ver. 15.0.0 or above is required  but on [sockets.sh](https://sockets.sh/) under Troubleshooting/Windows/Development Environment there is a link that points to older ver: 14.0.0 which build won't work with.

**Comment by mribbons** [comment]
Great, thanks @wujekbizon 🎉 
Happy developing, let us know how you go.

For anyone else reading, the current version downloads VS build tools (if you accept).

The next version (`"@socketsupply/socket": "0.0.32"`) and adds it to the toolchain for ssc.exe will register clang as the CXX provider, so you won't need to add it to your path via the `vcvars64.bat` (Which doesn't work with Powershell)

**Comment by wujekbizon** [comment]
Hey @mribbons ,
I know I said that everything is working but , I've got another issue here:😅 . 

The app is up and running but no content has been shown on  screen , except css I guess. 
I'm having a CORS policy error , shown on image bellow:

![error_socket](https://user-images.githubusercontent.com/97871150/221356064-caf8b94d-e50b-41f2-a0f4-57ad7871b6ce.png)

I think this is related to this imports:

```js
import process from 'socket:process'; // <---this
import os from 'socket:os'; // <--- this 

import { createRoot } from 'react-dom/client';
import React from 'react';

if (process.env.DEBUG) {
  console.log('started in debug mode');
}

function AppContainer() {
  return <h1>Hello, {os.platform()}!</h1>;
}

const root = createRoot(document.getElementById('root'));
root.render(<AppContainer />);

```

because when I manually import them from node_modules like this:


```js
import process from '../node_modules/@socketsupply/socket/process';
import os from '../node_modules/@socketsupply/socket/os';

import { createRoot } from 'react-dom/client';
```
everythings works,

![noerror_socket](https://user-images.githubusercontent.com/97871150/221356515-25090ad2-85ee-4f80-b553-3f37bbdb3b9a.png)

am' I missing something here? ,  should I run some kind of local HTTP server like DevTool suggesting to ?

**Comment by mribbons** [comment]
Hey @wujekbizon, the local HTTP server is advise from react-dev-tools.

I can confirm that I see the same error.

@chicoxyzzy ?

**Comment by mribbons** [comment]
@wujekbizon Can you give 
`npx create-socket-app` a try again?
We published a new version not long ago, I can see the CORS errors, but I do get Hello Windows content without having to modify anything in `node_modules`.

**Comment by wujekbizon** [comment]
@mribbons sure I'm on it , just give me a sec.

**Comment by mribbons** [comment]
@wujekbizon All good, just noticed you are running a react app. 
Confirming I get the same issue.

**Comment by wujekbizon** [comment]
@mribbons  Yes I'm running create-socket-app **react** , and I try, still the same.

**Comment by chicoxyzzy** [comment]
add this to the `index.html`
```html
    <meta
      http-equiv="Content-Security-Policy"
      content="connect-src http://* https://* ipc://* file://*;"
    >
```

**Comment by chicoxyzzy** [comment]
oh, we need to add it to the templates

**Comment by wujekbizon** [comment]
@mribbons , @chicoxyzzy It didn't help , please check the  image below, in a  top of my DevTools console , there is a whole path there , and I don't know why,  but I've got one extra slash character in there , maybe that's causing a problem for me? Correct me if I'm wrong, but it should start file://C:/User .... right?
![error](https://user-images.githubusercontent.com/97871150/221363108-142a7b79-5f7d-40fb-9db1-eef3826866bf.png)

**Comment by jwerle** [comment]
> @mribbons , @chicoxyzzy It didn't help , please check the image below, in a top of my DevTools console , there is a whole path there , and I don't know why, but I've got one extra slash character in there , maybe that's causing a problem for me? Correct me if I'm wrong, but it should start file://C:/User .... right? ![error](https://user-images.githubusercontent.com/97871150/221363108-142a7b79-5f7d-40fb-9db1-eef3826866bf.png)

hi @wujekbizon !

The leading slash after `file://` is correct

**Comment by mribbons** [comment]
@jwerle Confirming I see the same file:///x:/ type path at top of the inspector window.

The requests that fail are for:
```
Request URL: socket:process
Request URL: socket:os
```
The origin shows as `file://`

I tried adding file:// to the cors list, no improvament.

**Comment by mribbons** [comment]
@wujekbizon try putting this in `build.js`, then run `npm start`:

Please revert `index.html` back to the original state, or start with a freshly created app.

```js
//
// This is an example build script for Socket Runtime
// When you run 'ssc build', this script (node build.js) will be run
//
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'

import esbuild from 'esbuild'

const dirname = path.dirname(import.meta.url).replace(`file://${os.platform() === 'win32' ? '/' : ''}`, '')

console.log(`dirname: ${dirname}`);

const cp = async (a, b) => fs.promises.cp(
  path.resolve(a),
  path.join(b, path.basename(a)),
  { recursive: true, force: true }
)

async function main () {
  const prod = process.argv.find(s => s.includes('--prod'))

  const params = {
    entryPoints: ['src/index.jsx'],
    format: 'esm',
    bundle: true,
    minify: !!prod,
    sourcemap: !prod,
    external: ['node:*'],
    plugins: []

  }

  if (os.platform() !== 'win32') {
    params.external.push('socket:*')
  } else {
    params.plugins.push({
      name: 'socket-runtime-import-path',
      setup (build) {
        build.onResolve({ filter: /^socket:.*$/ }, (args) => {
          const basename = args.path.replace('socket:', '').replace(/.js$/, '') + '.js'
          const filename = `./socket/${basename}`
          return { path: filename, external: true }
        })
      }
    })
  }

  const watch = process.argv.find(s => s.includes('--watch='))

  //
  // The second argument to this program will be the target-OS specifc
  // directory for where to copy your build artifacts
  //
  const target = path.resolve(process.argv[2])

  //
  // If the watch command is specified, let esbuild start its server
  //
  if (watch) {
    esbuild.serve({ servedir: path.resolve(watch.split('=')[1]) }, params)
  }

  //
  //
  //
  if (!watch) {
    await esbuild.build({
      ...params,
      outfile: path.join(target, 'index.js')
    })
  }
  if (process.argv.find(s => s.includes('--test'))) {
    await esbuild.build({
      ...params,
      entryPoints: ['test/index.js'],
      outdir: path.join(target, 'test')
    })
  }

  //
  // Not writing a package json to your project could be a security risk
  //
  await fs.promises.writeFile(path.join(target, 'package.json'), '{ "type": "module", "private": true }')

  if (!target) {
    console.log('Did not receive the build target path as an argument!')
    process.exit(1)
  }

  //
  // Copy some files into the new project
  //
  await Promise.all([
    cp('src/index.html', target),
    cp('src/index.css', target),
    cp('src/icon.png', target)
  ])
}

main()
```

We need to redirect socket: to the local fs on Win32.

**Comment by wujekbizon** [comment]
@mribbons,  Success, it's working!  I did like you said , started with freshly created app, then replace build.js with the one you provided and npm start.  I can see the content, add new content and see new content appear on the screen  after reload of  the app.

**Comment by mribbons** [comment]
Great, thanks for the feedback @wujekbizon!

https://github.com/socketsupply/create-socket-app/pull/24 will resolve this problem. 

Feel free to take a look there if you want to get a `build.js` for any of the other supported frameworks.

**Comment by lamiazar** [comment]
resolved-closing.
